### ISSUE TITLE
Open a GitHub Page

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight-Website#13]
We need a GitHub page to host the website

**Comment by kryaksy** [comment]
On it!
https://pages.github.com

**Comment by maevanapcontact** [comment]
Great! Do you have all the access you need to create this website? I wonder if only the owner of the repository can do it. Tell me :)

**Comment by kryaksy** [comment]
I think I don't have access. But I am trying it for my repository to learn how can we do it:)
