### ISSUE TITLE
Have an index.html filled

### ISSUE THREAD

**Issue by maevanapcontact** [maevanapcontact/Ulight-Website#2]
We need a proper index.html file with the basic HTML structure and a link to the CSS file in assets/css/style.css

**Comment by SFromentarius** [comment]
![howtosortissues](https://user-images.githubusercontent.com/30386836/34222460-e6d3c860-e5bb-11e7-938b-691dfaf90c70.png)

**Comment by RA9** [comment]
I am interested and want to do it
